
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/root?characterEncoding = utf8
    username: root
    password: 0607
  jpa:
    database: MYSQL
    show-sql: true
  #Hibernate ddl auto (validate | create | create-drop | update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate: org.hibernate.dialect.MySQL5Dialect